# Generated by Django 6.0.5 on 2026-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('date_publication', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
